services:
  - type: web
    name: yeosu-coupon-system
    env: node
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: PORT
        value: 8080
